name = "icra-builders-v1"
main = "src/index.ts"
compatibility_date = "2026-06-29"
workers_dev = false
preview_urls = false

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"
run_worker_first = true

[[routes]]
pattern = "icra.builders"
zone_name = "icra.builders"

[[routes]]
pattern = "www.icra.builders"
zone_name = "icra.builders"
